from django.conf import settings
import stripe
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from library.models import Book
from purchase.models import Purchase


class PaymentView(APIView):
    def post(self, request):
        stripe.api_key = settings.STRIPE_SECRET_KEY
        try:
            # Retrieve payment details from the request
            amount = request.data.get('amount')
            token = request.data.get('token')  # Payment token generated by frontend

            # Create a charge using Stripe API
            charge = stripe.Charge.create(
                amount=amount,
                currency='usd',
                description='Payment for book purchase',
                source=token,  # Payment token generated by frontend
            )

            # Save purchase information
            book_id = request.data.get('book_id')
            book = Book.objects.get(id=book_id)
            purchase = Purchase.objects.create(
                book=book,
                buyer=request.user,
                payment_method='Mastercard',  # Example payment method
            )
            purchase.save()

            return Response({'message': 'Payment successful'}, status=status.HTTP_200_OK)

        except stripe.error.CardError as e:
            body = e.json_body
            err = body.get('error', {})
            return Response({'error': err.get('message')}, status=status.HTTP_400_BAD_REQUEST)

        except stripe.error.StripeError as e:
            return Response({'error': 'Payment failed'}, status=status.HTTP_400_BAD_REQUEST)


clas